name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build
    runs-on: [self-hosted, dotnet, Windows, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build binary
        run: msbuild AlgoliaCrawler.sln /p:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            AlgoliaCrawler/bin/Release/*.exe
            AlgoliaCrawler/bin/Release/*.json